apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 024916728325.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 024916728325.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: afa55da4
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
